markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
exclude:
  - vendor
rdiscount:
  extensions: [ autolink, footnotes, smart ]

syntax-highlighting:
  enabled : true
  css: solarized-light.css

